config/routes.rb
Rails.application.routes.draw do
root 'chatrooms#index'

get '/sign_in' => 'sessions#new', as: :sign_in
post '/sign_in' => 'sessions#create'
delete '/sign_out' => 'sessions#delete', as: :sign_out

get 'chatrooms/:id' => 'chatrooms#show', as: :chatroom

get "/sign_up" => 'users#new', as: :sign_up
post "/sign_up" => 'users#create', as: :users

namespace :api do
    get "chatrooms/:id" => 'chatrooms#show'
     post "chatrooms/:id/messages" => 'messages#create'
  end

end

app/models/chatroom.rb
class Chatroom < ActiveRecord::Base
      has_many :messages
      has_many :users
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :messages

  validates :username, presence: true
  validates :password, presence: true
  validates :email, presence: true
end

app/controllers/api/chatrooms_controller.rb
class Api::ChatroomsController < ApplicationController

  before_action :authenticate_user!

  def show
    @chatroom = Chatroom.find params[:id]
  end


end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController

before_action :authenticate_user!

  def create
      @message = Message.new params.require(:message).permit(:text)
      @message.chatroom = Chatroom.find params[:id]
      @message.user = @current_user
      if @message.save
         render status: 201, json: @message
      else
        render status: 422, json: @message.errors
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    redirect_to sign_in_path unless user_signed_in?
  end

  def sign_in user
    session[:user_id] = user.id
  end

  def sign_out
    session.delete :user_id
  end

  def user_signed_in?
    @current_user.present?

  end
  helper_method :user_signed_in?

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  before_action :authenticate_user!

  def index
    @chatrooms = Chatroom.all
  end

  def show
     @chatrooms = Chatroom.all
     @chatroom = Chatroom.find params[:id]
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create

     email = params[:email]
     password = params[:password]

     user = User.find_by email: email
     if user && user.authenticate(password)
       session[:user_id] = user.id
       redirect_to root_path
     else
       flash.now[:alert] = "incorrect email or password"
       render :new
     end
   end

  




 def delete
    session.delete :user_id
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:email, :password, :password_confirmation, :username)
    if @user.save
      sign_in @user
      redirect_to root_path, notice: "Welcome to darkzone, #{@user.email}"
    else
      render :new
    end
  end

end

app/helpers/api/chatrooms_helper.rb
module Api::ChatroomsHelper
end

app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zone_helper.rb
module ZoneHelper
end

app/views/chatrooms/index.html.erb
<div class="page-header">
  <h1>Darkzone <small>messngr updates</small></h1>
  <small class="text-right"><%= link_to "Sign Out", sign_out_path, method: :delete %></small>
</div>


  <div class="col-md-2">
      Chatrooms
    <div class="vleft">
     <ul class="list-group">
        <% @chatrooms.each do |chatroom| %>
      <li class="list-group-item"> <%= link_to chatroom.roomname, chatroom_path(id: chatroom.id) %></li>
        <% end %>
    </ul>
    </div>
  </div>

app/views/chatrooms/show.html.erb
<div class="page-header">
  <h1>Darkzone <small>messngr updates</small></h1>

<small class="text-right"><%= link_to "Sign Out", sign_out_path, method: :delete %></small>
</div>


  <div class="col-md-2">
    Chatrooms
    <div class="vleft">

     <ul class="list-group">
        <% @chatrooms.each do |chatroom| %>
      <li class="list-group-item"> <%= link_to chatroom.roomname, chatroom_path(id: chatroom.id) %></li>
        <% end %>
    </ul>
    </div>
  </div>


<%= react_component 'TopLevel', {chatroom: @chatroom} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Darkzone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container">
  <div className="row">
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Darkzone <small>messngr updates (sign up)</small></h1>
</div>

<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: "Password Confirmation" %>
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>